resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

resources:
- name: artifact-repo
  type: maven-resource
  source:
    url: http://192.168.1.36:8081/nexus/content/repositories/snapshots
    artifact: com.example:demo:jar
    username: admin
    password: admin123
- name: source-code-repo
  type: git
  source:
    uri: https://github.com/alejandro-quesada/con-workshop.git
    branch: master


jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: tasks/build.yml
  - put: artifact-repo
    params:
      file: build-artifact/*.jar
      pom_file: source-code/pom.xml